presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.14.3
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "300m"
  - name: thoth-pytest-py38
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pytest
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-pytest-py38:v0.14.3
          command:
             - "/bin/run-pytest"
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 300m
              memory: 400Mi
